# Wavelet Packet Decomposition And Tensorflow

## Preprocessing

### Handle datasets

In [2]:
from scipy.io import loadmat
import os
import numpy as np

SAMPLE_RATE = 250
path = "./MI_ST/A01T.mat"
with open(path)
MAX_SAMPLE = 19680  # cut the data to algin
NUM_OF_CHANNEL = 5
X = np.array([])
counter = 0
exclude = ["R01", "R02", "R03", "R05", "R07", "R09", "R11", "R13", "R15"]
CURRENT_DIR = os.getcwd()

all_dirs = sorted(os.listdir('MI'))
for dirs in all_dirs:
    for j in sorted(os.listdir(os.path.join('MI', dirs))):
        path = os.path.join(CURRENT_DIR , 'MI', dirs, j)
        if j[4:7] not in exclude:
            with pyedflib.EdfReader(path) as f:
                n = f.signals_in_file
                signal_labels = f.getSignalLabels()
                sigbufs = np.zeros((MAX_SAMPLE, NUM_OF_CHANNEL))
                for i in np.arange(NUM_OF_CHANNEL):
                    sigbufs[:, i] = f.readSignal(i+7)[:MAX_SAMPLE]
                X = np.append(X, sigbufs)
            counter += 1
            if counter >= 6*56:
                break
    if counter >= 6*56:
        break

SyntaxError: invalid syntax (<ipython-input-2-7f8a360df79a>, line 7)

In [52]:
import numpy as np
from numpy import sqrt
A = np.array([[0 ,1],
              [1, 1],
              [1, 0]])

At = np.linalg.inv(np.matmul(np.transpose(A), A))

H = np.matmul(A, At)
P = np.matmul(H, np.transpose(A))
print(2*P - np.identity(3))

[[ 0.33333333  0.66666667 -0.66666667]
 [ 0.66666667  0.33333333  0.66666667]
 [-0.66666667  0.66666667  0.33333333]]


In [80]:
A = np.array([[2, 3], [4, 7], [2, 4]])
At = np.matmul(np.transpose(A), A)
print(At)
Ai = np.linalg.inv(At)
b = np.array([3, 5, 3])
P = np.dot(Ai, np.transpose(A))

li = np.dot(P, A)
print(P)
x = np.dot(P, np.transpose(b))
x

[[24 42]
 [42 74]]
[[ 1.83333333  0.16666667 -1.66666667]
 [-1.          0.          1.        ]]


array([1.33333333, 0.        ])

In [87]:
from numpy import pi, power

B = np.array([[1, 0, 0], [-1, 1, 0],[0, -1, 1], [1, 0, -1]])

q, r = np.linalg.qr(B)
print(q)
print(r)

[[-0.57735027 -0.25819889 -0.77459667]
 [ 0.57735027 -0.51639778 -0.25819889]
 [-0.          0.77459667 -0.25819889]
 [-0.57735027 -0.25819889  0.51639778]]
[[-1.73205081  0.57735027  0.57735027]
 [ 0.         -1.29099445  1.03279556]
 [ 0.          0.         -0.77459667]]


In [90]:
B = np.array([[1, -1, 0, 0], [1, -1, 0, 0] ,[1, 0, -1, 0], [1, 0, 0, -1], 
              [0, 1, -1, 0], [0, 1, 0, -1], [0, 0, 1, -1]])

Bt = np.transpose(B)
Be = np.dot(Bt, B)
np.linalg.inv(Be)

LinAlgError: Singular matrix